language: objective-c
xcode_project: ArrayLoaderInterface.xcodeproj
xcode_scheme: ArrayLoaderInterface
osx_image: xcode7.2
before_install: true
install: true
git:
  submodules: false
script:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.15/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - /usr/local/bin/carthage bootstrap --platform iOS
  - xctool -project ArrayLoaderInterface.xcodeproj -scheme ArrayLoaderInterface