language: objective-c
xcode_project: ArrayLoaderInterface.xcodeproj
xcode_scheme: ArrayLoaderInterface
osx_image: xcode7.3
before_install: true
install: true
git:
  submodules: false
script:
  - /usr/local/bin/carthage bootstrap --platform iOS --no-use-binaries
  - xctool -sdk iphonesimulator -project ArrayLoaderInterface.xcodeproj -scheme ArrayLoaderInterface
